export const NAVIGATION = {
  COMINGSOON: {
    INDEX: "COMINGSOON_INDEX",
    SCREEN1: "COMINGSOON_SCREEN1",
    SCREEN2: "COMINGSOON_SCREEN2",
    SCREEN3: "COMINGSOON_SCREEN3",
    SCREEN4: "COMINGSOON_SCREEN4",
    SCREEN5: "COMINGSOON_SCREEN5",
    SCREEN6: "COMINGSOON_SCREEN6",
  },
};
